FROM node:16.14.0-alpine

# Note that we will specify NX_API_URL on the command line
EXPOSE 4201

WORKDIR /app
COPY . .

RUN npm install -g nx
RUN npm install

RUN nx build cart --configuration=production

CMD [ "nx", "serve", "cart" ]
