FROM node:16.14.0-alpine

WORKDIR /app
COPY . .

RUN npm install -g nx
RUN npm install

RUN nx build proshop-api --configuration=production

# Overrides hard-coded port 3333 in code
ENV PORT 8080
EXPOSE ${PORT}

CMD [ "node", "dist/apps/proshop-api/main.js" ]
