FROM node:16.14.0-alpine

ENV NX_API_PORT 8080
EXPOSE ${NX_API_PORT}

WORKDIR /app
COPY . .

RUN npm install -g nx
RUN npm install

RUN nx build proshop-api --configuration=production

CMD [ "nx", "serve", "proshop-api" ]
