version: '3.8'

services:
  proshop-proxy:
    image: nginx:1.21.6-alpine
    volumes:
      - $PWD/proxy/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
    depends_on:
      - proshop-catalog
      - proshop-cart
      - proshop-api

  proshop-catalog:
    image: nareshbhatia/proshop-nx-catalog:1.0.0
    environment:
      - NX_SERVER_SIDE_API_URL=http://proshop-api:8080
      - NX_CLIENT_SIDE_API_URL=/graphql
    depends_on:
      - proshop-api

  proshop-cart:
    image: nareshbhatia/proshop-nx-cart:1.0.0
    environment:
      - NX_SERVER_SIDE_API_URL=http://proshop-api:8080
      - NX_CLIENT_SIDE_API_URL=/graphql
    depends_on:
      - proshop-api

  proshop-api:
    image: nareshbhatia/proshop-nx-api:1.0.0
