apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-deployment
  labels:
    app: cart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
      - name: cart
        image: nareshbhatia/proshop-nx-cart:1.0.0
        ports:
        - containerPort: 3002
        env:
        - name: NX_API_URL
          valueFrom:
            configMapKeyRef:
              name: proshop-api-config
              key: proshop-api-url
---
apiVersion: v1
kind: Service
metadata:
  name: cart-service
spec:
  type: NodePort
  selector:
    app: cart
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
      nodePort: 30002
